apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "url-monitor.fullname" . }}
  labels:
    app: {{ include "url-monitor.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "url-monitor.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "url-monitor.name" . }}
    spec:
      containers:
      - name: {{ include "url-monitor.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
